# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development: &development
  adapter: mysql2
  host: localhost
  username: root
  password: 123qwe
  database: mad2_developement

test: &test
  adapter: mysql2
  host: localhost
  username: root
  password: 123qwe
  database: mad2_test

production:
  adapter: mysql2
  host: localhost
  username: root
  password: 123qwe
  database: mad2_developement
